image: ghcr.io/cirrusci/flutter:stable

stages:
  - test
  - build

variables:
  PUB_BUILD_DIR: "build"

before_script:
  - flutter doctor -v
  - flutter pub get

unit_tests:
  stage: test
  script:
    - flutter test

build_apk:
  stage: build
  script:
    - BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ')
    - flutter build apk --release --dart-define=GIT_COMMIT="$CI_COMMIT_SHA" --dart-define=GIT_TAG="${CI_COMMIT_TAG:-$CI_COMMIT_REF_NAME}" --dart-define=BUILD_DATE="$BUILD_DATE"
  artifacts:
    name: "app-release-$CI_COMMIT_REF_SLUG"
    paths:
      - build/app/outputs/flutter-apk/app-release.apk
    expire_in: 1 week
